#!/usr/bin/env sh

_() {
  USERNAME=""
  ACCESS_TOKEN=""

  echo "GitHub Username: "
  read -r USERNAME
#  echo "GitHub Access token: "
#  read -r ACCESS_TOKEN

  [ -z "$USERNAME" ] && exit 1
#  [ -z "$ACCESS_TOKEN" ] && exit 1

  for YEAR in $(seq 2015 2023); do
    git init
    echo "**${YEAR}** - Generated by https://github.com/vertocode/i-love-commit" \
      >README.md
    git add .
    GIT_AUTHOR_DATE="${YEAR}-01-01T18:00:00" \
      GIT_COMMITTER_DATE="${YEAR}-01-01T18:00:00" \
      git commit -m "${YEAR}"

    for MONTH in {01..12}; do
      for DAY in {01..31}; do
        DATE="${YEAR}-${MONTH}-${DAY}T12:00:00"
        GIT_AUTHOR_DATE="$DATE" \
          GIT_COMMITTER_DATE="$DATE" \
          echo "**${DATE}** - Commit message for ${DATE}" \
          >README.md
        git add .
        git commit -m "Commit on ${DATE}"
      done
    done
  done

  git remote add origin "https://${ACCESS_TOKEN}@github.com/${USERNAME}/i-love-commit.git"
  git branch -M main
  git push -u origin main -f
  cd ..
  rm -rf "${YEAR}"

  echo
  echo "Cool, check your profile now: https://github.com/${USERNAME}"
} && _

unset -f _
